development:
  uri: mongodb://localhost
  database: app_dev
  logfile: development.log
    
production:
  uri: mongodb://localhost
  database: app_prod
  logfile: production.log
    
environment: development
